version: "3.8"
services:
  backend:
    container_name: car-dealership-backend:v0.0.1
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    container_name: car-dealership-frontend:v0.0.1
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend